### ISSUE TITLE
Error when trying to get dev enviroment working 

### ISSUE THREAD

**Issue by cassiopaia** [ethereum/meteor-dapp-wallet#144]
When trying to start meteor-dapp-wallet by fire up

`meteor --port 3050`

i'm getting following error : 

```/Users/xx/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:278
						throw(ex);
						      ^
Error: EACCES, unlink '/Users/xx/Git/meteor-dapp-wallet/app/.meteor/local/build/.node_version.txt'
    at Object.Future.wait (/Users/xx/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:398:15)
    at Object.rm_recursive (/tools/fs/files.js:270:9)
    at Command.main.registerCommand.name [as func] (/tools/cli/commands.js:1211:9)
    at /tools/cli/main.js:1378:23```

Any idea how to proceed?

**Comment by luclu** [comment]
This seems to be a permission error.
Look [here](https://stackoverflow.com/questions/34007283/error-eacces-unlink).
