### ISSUE TITLE
meteor tap_i18n-bundler error on windows

### ISSUE THREAD

**Issue by haldhar** [ethereum/meteor-dapp-wallet#147]
=> Started proxy.
=> Started MongoDB.
=> Exited with code: 8
W20160415-15:01:39.688(5.5)? (STDERR)
W20160415-15:01:39.689(5.5)? (STDERR) C:\Users\haldhar.seth\AppData\Local.meteo
r\packages\meteor-tool\1.3.1\mt-os.windows.x86_32\dev_bundle\server-lib\node_mod
ules\fibers\future.js:245
W20160415-15:01:39.689(5.5)? (STDERR)
throw(ex);
W20160415-15:01:39.689(5.5)? (STDERR)
      ^
W20160415-15:01:39.690(5.5)? (STDERR) Error: ENOENT, no such file or directory '
C:\Haldhar\meteor\meteor-dapp-wallet-master\app.meteor\local\build\programs\ser
ver\undefined\public'
W20160415-15:01:39.690(5.5)? (STDERR)     at Object.fs.mkdirSync (fs.js:654:18)
W20160415-15:01:39.690(5.5)? (STDERR)     at Package (packages/tap_i18n-bundler/
i18n-bundler.coffee:18:12)
W20160415-15:01:39.690(5.5)? (STDERR)     at C:\Haldhar\meteor\meteor-dapp-walle
t-master\app.meteor\local\build\programs\server\boot.js:290:5
W20160415-15:01:45.446(5.5)? (STDERR) C:\Users\haldhar.seth\AppData\Local.meteo
r\packages\meteor-tool\1.3.1\mt-os.windows.x86_32\dev_bundle\server-lib\node_mod
ules\fibers\future.js:245
W20160415-15:01:45.446(5.5)? (STDERR)
W20160415-15:01:45.447(5.5)? (STDERR)
throw(ex);
W20160415-15:01:45.447(5.5)? (STDERR)
      ^
W20160415-15:01:45.447(5.5)? (STDERR) Error: ENOENT, no such file or directory '
C:\Haldhar\meteor\meteor-dapp-wallet-master\app.meteor\local\build\programs\ser
ver\undefined\public'
W20160415-15:01:45.447(5.5)? (STDERR)     at Object.fs.mkdirSync (fs.js:654:18)
W20160415-15:01:45.447(5.5)? (STDERR)     at Package (packages/tap_i18n-bundler/
i18n-bundler.coffee:18:12)
W20160415-15:01:45.447(5.5)? (STDERR)     at C:\Haldhar\meteor\meteor-dapp-walle
t-master\app.meteor\local\build\programs\server\boot.js:290:5
=> Exited with code: 8
W20160415-15:01:55.388(5.5)? (STDERR)
W20160415-15:01:55.391(5.5)? (STDERR) C:\Users\haldhar.seth\AppData\Local.meteo
r\packages\meteor-tool\1.3.1\mt-os.windows.x86_32\dev_bundle\server-lib\node_mod
ules\fibers\future.js:245
W20160415-15:01:55.391(5.5)? (STDERR)
throw(ex);
W20160415-15:01:55.391(5.5)? (STDERR)
      ^
W20160415-15:01:55.392(5.5)? (STDERR) Error: ENOENT, no such file or directory '
C:\Haldhar\meteor\meteor-dapp-wallet-master\app.meteor\local\build\programs\ser
ver\undefined\public'
W20160415-15:01:55.392(5.5)? (STDERR)     at Object.fs.mkdirSync (fs.js:654:18)
W20160415-15:01:55.392(5.5)? (STDERR)     at Package (packages/tap_i18n-bundler/
i18n-bundler.coffee:18:12)
W20160415-15:01:55.392(5.5)? (STDERR)     at C:\Haldhar\meteor\meteor-dapp-walle
t-master\app.meteor\local\build\programs\server\boot.js:290:5
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.

**Comment by PranobSamani** [comment]
remove i18 dependency by using this command  'meteor remove tap:i18n-bundler' it should work

**Comment by IgorShadurin** [comment]
after removing tap:i18n-bundler, meteor starts but after electron run, app show main form and after 1 second closed

**Comment by PranobSamani** [comment]
Please start the application in wallet mode

**Comment by luclu** [comment]
Does this problem still occur as of meteor `1.3.2.4`?

**Comment by luclu** [comment]
This should be solved on `develop`/`master`.

**Comment by charly37** [comment]
I think it happen again (MASTER cloned 10june2017):
https://github.com/ethereum/mist/issues/2491

**Comment by evertonfraga** [comment]
@charly37 confirmed, it happens again.

**Comment by dpyro** [comment]
Same here on a fresh git clone.

**Comment by stvenyin** [comment]
usually,i use netstat –ano|findstr 3000
netstat -antep | findstr 3002
tasklist|findstr 3000
meteor reset
rm-rf .meteor/local/db/mongod.lock
rm -rf .meteor/local/db/
meter restat
meteor


meteor npm install --save-exact @babel/runtime@7.0.0-beta.55
meteor npm install @babel/runtime@7.0.0-beta.55

if appear  
![Uploading 1.jpg…]()

**Comment by stvenyin** [comment]
![1](https://user-images.githubusercontent.com/32395964/54065066-25c81100-4256-11e9-9bea-13c959c20417.jpg)
