### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by amitOodles** [ethereum/meteor-dapp-wallet#375]
Mist version: 0.8.9
Electron version: 1.3.13
[11:57:23] Using gulpfile ~/Documents/Decentralised/rohitMistFork/mist/gulpfile.js
[11:57:23] Starting 'buildQueue'...
[11:57:23] Starting 'clean-dist'...
[11:57:23] Finished 'clean-dist' after 18 ms
[11:57:23] Starting 'copy-app-source-files'...
[11:57:24] Finished 'copy-app-source-files' after 714 ms
[11:57:24] Starting 'copy-build-folder-files'...
[11:57:24] Finished 'copy-build-folder-files' after 12 ms
[11:57:24] Starting 'switch-production'...
[11:57:24] Finished 'switch-production' after 1.79 ms
[11:57:24] Starting 'bundling-interface'...
Use local wallet at ../meteor-dapp-wallet/app
Bundling Meteor app...
Generating the index.html...
Done!
-----
You can find your files in "/home/amit/Documents/Decentralised/rohitMistFork/mist/dist_wallet/app/interface".
Bundling Meteor app...
Failed to execute "meteor build ../../mist/dist_wallet/app/interface/wallet --directory", exit code of #1

[12:01:23] 'bundling-interface' errored after 3.98 min
[12:01:23] Error: Command failed: cd interface             && meteor-build-client ../dist_wallet/app/interface -p ""             && cd ../../meteor-dapp-wallet/app                 && meteor-build-client ../../mist/dist_wallet/app/interface/wallet -p ""
 Errors prevented bundling:
While minifying app code:

/home/amit/.meteor/packages/standard-minifier-js/.1.0.6.47eoz0++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/lib/parse.js:196:18:
Unexpected token: operator (>)
at new JS_Parse_Error
(/home/amit/.meteor/packages/standard-minifier-js/.1.0.6.47eoz0++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/lib/parse.js:196:18)
at js_error
(/home/amit/.meteor/packages/standard-minifier-js/.1.0.6.47eoz0++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/lib/parse.js:204:11)
at croak
(/home/amit/.meteor/packages/standard-minifier-js/.1.0.6.47eoz0++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/lib/parse.js:675:9)
at token_error
(/home/amit/.meteor/packages/standard-minifier-js/.1.0.6.47eoz0++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/lib/parse.js:683:9)
at unexpected
(/home/amit/.meteor/packages/standard-minifier-js/.1.0.6.47eoz0++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/lib/parse.js:689:9)
at expr_atom
(/home/amit/.meteor/packages/standard-minifier-js/.1.0.6.47eoz0++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/lib/parse.js:1196:9)
at maybe_unary
(/home/amit/.meteor/packages/standard-minifier-js/.1.0.6.47eoz0++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/lib/parse.js:1358:19)
at expr_ops
(/home/amit/.meteor/packages/standard-minifier-js/.1.0.6.47eoz0++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/lib/parse.js:1393:24)
at maybe_conditional
(/home/amit/.meteor/packages/standard-minifier-js/.1.0.6.47eoz0++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/lib/parse.js:1398:20)
at maybe_assign
(/home/amit/.meteor/packages/standard-minifier-js/.1.0.6.47eoz0++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/lib/parse.js:1422:20)

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by evertonfraga** [comment]
This should be resolved as of now. Can you check, after executing `git pull`?

**Comment by amitOodles** [comment]
I figured it out that it was due to the arrow function syntax and replaced the arrow function with regular function syntax . 
You can close this if the above issue is resolved .
