### ISSUE TITLE
Error: The babel-runtime npm package could not be found in your node_modules

### ISSUE THREAD

**Issue by jordaniac89** [ethereum/meteor-dapp-wallet#425]
Stacktrace 

```
W20171103-11:05:40.281(-5)? (STDERR) Error: The babel-runtime npm package could not be found in your node_modules 
W20171103-11:05:40.282(-5)? (STDERR) directory. Please run the following command to install it:
W20171103-11:05:40.282(-5)? (STDERR) 
W20171103-11:05:40.283(-5)? (STDERR)   meteor npm install --save babel-runtime
W20171103-11:05:40.283(-5)? (STDERR) 
W20171103-11:05:40.284(-5)? (STDERR)     at babel-runtime.js (packages/babel-runtime.js:36:9)
W20171103-11:05:40.284(-5)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20171103-11:05:40.284(-5)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20171103-11:05:40.285(-5)? (STDERR)     at packages/babel-runtime.js:155:15
W20171103-11:05:40.285(-5)? (STDERR)     at packages/babel-runtime.js:166:3
W20171103-11:05:40.286(-5)? (STDERR)     at infos.forEach.info (/Users/jordanmiles/Documents/meteor-dapp-wallet/app/.meteor/local/build/programs/server/boot.js:414:13)
W20171103-11:05:40.286(-5)? (STDERR)     at Array.forEach (<anonymous>)
W20171103-11:05:40.286(-5)? (STDERR)     at /Users/jordanmiles/Documents/meteor-dapp-wallet/app/.meteor/local/build/programs/server/boot.js:413:9
W20171103-11:05:40.287(-5)? (STDERR)     at /Users/jordanmiles/Documents/meteor-dapp-wallet/app/.meteor/local/build/programs/server/boot.js:463:5
W20171103-11:05:40.287(-5)? (STDERR)     at Function.run (/Users/jordanmiles/Documents/meteor-dapp-wallet/app/.meteor/local/build/programs/server/profile.js:510:12)
```
I do not know if these is a dapp-wallet issue or a meteor issue. I only started receiving this when I updated meteor and tried to start the dapp-wallet again.

**Comment by jordaniac89** [comment]
Resolved this by running the requested command `meteor npm install --save babel-runtime` in the directory ./app/.meteor/local/build/programs/server/.

**Comment by jordaniac89** [comment]
Nevermind. Starting up the app and going to localhost:3000 results in a blank page with no console output.

**Comment by LeNiglo** [comment]
@jordaniac89 , any clue ?

**Comment by riv333** [comment]
I had the same problem and I fixed it by using the babel ^7.0.0-beta.42 Version. When I execute the meteor npm install --save babel-runtime in the root directory I get the "babel-runtime": "^6.26.0” Version which seems not to be compatible with the newest meteor 1.6.1.1 Release.

Step by step:

1. 
cd in project folder and:
`meteor update`

2. 
If not exists add package.json to your meteor project (if an package-lock.json exists delete it):
```
{
  "name": "app",
  "private": true,
  "scripts": {
    "start": "meteor run"
  },
  "dependencies": {
    "@babel/runtime": "^7.0.0-beta.42",
    "meteor-node-stubs": "^0.3.2"
  }
}
```
3.
in project folder:
`meteor npm install`

4. 
For the database refresh maybe (attention deletes all data from database!):
`meteor reset`

**Comment by stvenyin** [comment]
meteor npm install --save babel-runtime!
